name: Development CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run debug unit tests
        run: ./gradlew testDebugUnitTest

      - name: Run detekt
        run: ./gradlew detekt

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload debug test report
        uses: actions/upload-artifact@v4
        with:
          name: debug-unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/index.html

      - name: Upload detekt report
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: app/build/reports/detekt/detekt.html

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk